name: Cody Tesnow
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Cody Tesnow - Writer. Creative. Rabblerouser. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5189846-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2559a2'
    - '#ae9e84'
    - '#5faee9'
    - '#aae4fa'
    - '#6f7070'
  brandStrength: 0.734673359664157
  lightness: 0.5366962447296828
  saturation: 0.9973775411490351
  rhythmicContrast: 0.19192826398648322
purpose: []
