name: Cody Tesnow
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Cody Tesnow - Writer. Creative. Rabblerouser. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5189846-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2559a2'
    - '#ae9e84'
    - '#5faee9'
    - '#aae4fa'
    - '#6f7070'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
